parameter_defaults:
  #CinderRbdPoolName: esi
  #CinderBackupRbdPoolName: esi
  #CephClientUserName: admin

  CephExternalMonHost: 10.30.3.1

  LocalCephAnsibleFetchDirectoryBackup: /tmp/ceph_ansible_fetch

  # Disable ceph for cinder, because it's not supported for boot-from-volume
  # with ironic.
  CinderEnableRbdBackend: true
  #CinderEnableIscsiBackend: true
  #CinderBackupBackend: swift
