parameter_defaults:
  NovaRbdPoolName: esi
  CinderRbdPoolName: esi
  CinderBackupRbdPoolName: esi
  GlanceRbdPoolName: esi
  GnocchiRbdPoolName: esi
  CephClientUserName: admin

  CephExternalMonHost: '192.168.16.1,192.168.16.2,192.168.16.3'

  LocalCephAnsibleFetchDirectoryBackup: /tmp/ceph_ansible_fetch

  # Disable ceph for cinder, because it's not supported for boot-from-volume
  # with ironic.
  CinderEnableRbdBackend: false
  CinderEnableIscsiBackend: true
  CinderBackupBackend: swift
