parameter_defaults:
  NovaRbdPoolName: esi
  CinderRbdPoolName: esi
  CinderBackupRbdPoolName: esi
  GnocchiRbdPoolName: esi
  CephClientUserName: admin

  LocalCephAnsibleFetchDirectoryBackup: /tmp/ceph_ansible_fetch

  GlanceBackend: swift
