parameter_defaults:
  DockerMistralApiImage: 192.168.1.2:8787/moc/centos-binary-mistral-api:rocky-ironic-traits
  DockerMistralExecutorImage: 192.168.1.2:8787/moc/centos-binary-mistral-executor:rocky-ironic-traits
  DockerNovaComputeImage: 192.168.1.2:8787/moc/centos-binary-nova-compute:I907b69eb689cf6c169a4869cfc7889308ca419d5
  DockerNovaComputeIronicImage: 192.168.1.2:8787/moc/centos-binary-nova-compute-ironic:I907b69eb689cf6c169a4869cfc7889308ca419d5
